### PR TITLE
Don't print nil

### PR DESCRIPTION
**Pull request by crackcomm**
Maybe someone could need it but I think most don't.

### CODE REVIEW

**Comment by aybabtme** [comment]
Do you have an example use case where this is preferable?

**Comment by crackcomm** [comment]
Im using barchart to print statistics and I don't want printed all values just the values that I will add.

**Comment by aybabtme** [comment]
Can you make it configurable? There are cases where I want to see the `nil` entries, and I'd also like to support your use case. Maybe make it an option on the `BarChart` struct?

**Comment by aybabtme** [comment]
ping @crackcomm

**Pull request closed without merging**
