### PR TITLE
Tab-align histogram into column

### PR DESCRIPTION
**Pull request by ryanseys**
Hey @aybabtme awesome lib. I'm dabbling in Go so excuse my terribly succinct PR. :)

Just wanted to column-align everything in the histogram view. Here's a screenshot:

screen shot 2015-03-21 at 3 14 53 am

Feel free to close if you don't agree with this choice. Just figured it fit with the fact that everything else was in columns. Also ran into a couple issues where the text was really close to the blocks and just looked kinda messy. Here's what I saw without tab aligning:

screen shot 2015-03-21 at 3 17 27 am

See how the 106 is just more close to the blocks than the other numbers... It's a total nitpick but none-the-less. :v:

### CODE REVIEW

**Comment by aybabtme** [comment]
LGTM, would you mind fixing the example =P

```
$ cd $GOPATH/src/github.com/aybabtme/uniplot/histogram
$ go test .
--- FAIL: ExampleHist (0.00s)
got:
0.1-0.2  5%   ▋       1
0.2-0.3  25%  ██▊     5
0.3-0.4  0%   ▏
0.4-0.5  5%   ▋       1
0.5-0.6  45%  █████▏  9
0.6-0.7  5%   ▋       1
0.7-0.8  0%   ▏
0.8-0.9  5%   ▋       1
0.9-1    10%  █▏      2
want:
0.1-0.2  5%   ▋1
0.2-0.3  25%  ██▊5
0.3-0.4  0%   ▏
0.4-0.5  5%   ▋1
0.5-0.6  45%  █████▏9
0.6-0.7  5%   ▋1
0.7-0.8  0%   ▏
0.8-0.9  5%   ▋1
0.9-1    10%  █▏2
--- FAIL: ExampleHist_duration (0.00s)
got:
100ms-200ms  4.55%  ▋       1
200ms-300ms  27.3%  ███▍    6
300ms-400ms  4.55%  ▋       1
400ms-500ms  4.55%  ▋       1
500ms-600ms  40.9%  █████▏  9
600ms-700ms  4.55%  ▋       1
700ms-800ms  0%     ▏
800ms-900ms  4.55%  ▋       1
900ms-1s     9.09%  █▏      2
want:
100ms-200ms  4.55%  ▋1
200ms-300ms  27.3%  ███▍6
300ms-400ms  4.55%  ▋1
400ms-500ms  4.55%  ▋1
500ms-600ms  40.9%  █████▏9
600ms-700ms  4.55%  ▋1
700ms-800ms  0%     ▏
800ms-900ms  4.55%  ▋1
900ms-1s     9.09%  █▏2
```

(test in `spark/` is broken for some reason, so ignore it)

**Comment by ryanseys** [comment]
:cry: 

screen shot 2015-03-21 at 4 00 13 am

**Comment by aybabtme** [comment]
likely tabs vs spaces =P (does your editor convert tabs to spaces on save?)

**Comment by ryanseys** [comment]
How's that look? I had to remove the "Output:" from the tests for some reason and then the tests passed.

**Comment by aybabtme** [comment]
lgtm!

**Comment by ryanseys** [comment]
_tips fedora_

**Pull request merged**
